repos:
  - repo: local
    hooks:
      - id: erlfmt-check
        name: erlfmt check
        entry: rebar3 fmt --check
        language: system
        files: \.(erl|hrl|config|app.src)$
        pass_filenames: false
